version: '3.8'

name: learning-go-project
services:
  mongodb:
    image: mongo:latest
    container_name: learning-go-mongodb
    restart: always
    volumes:
      - mongodb-data-volume:/data/db
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - '27017:27017'

networks:
  default:
    name: learning-go-network

volumes:
  mongodb-data-volume: